#164069237 users should be able to bookmark articles for reading later
andela/Ah-backend-aquaman pull request #39
Opened 2019-03-19 18:23 UTC by Peace-Apple

## What does this PR do?
This PR adds a feature that enables a user to bookmark an article for reading later, view a list of their bookmarks and delete a bookmarked article from their list.

## How should this be manually tested?

- Clone this repository
- cd into the directory Ah-backend-aquaman
- Checkout the branch ft-bookmark-article-164069237
- Create and activate your virtual environment
- pip install -r requirements.txt
- python manage.py makemmigrations
- python manage.py migrate
- Source your .env file
- python manage.py runserver
- Sign up, verify your email and login
- To bookmark an article navigate to the endpoint http://127.0.0.1:8000/api/articles/articleslug/bookmark/ and make a post request
- To retrieve a list of your bookmarks go to http://127.0.0.1:8000/api/bookmarks/ and make a get request
- To delete a bookmarked article from your bookmarks list http://127.0.0.1:8000/api/articles/articleslug/bookmark/ and make a delete request

## What are the relevant pivotal tracker stories?

[#164069237](https://www.pivotaltracker.com/story/show/164069237)

## Screenshots

Ensure to paste your auth token into the token field for all the following endpoints

To bookmark an article, copy the article slug and attach it to your URL as shown

![image](https://user-images.githubusercontent.com/42435346/54631216-95c36c00-4a8c-11e9-808a-7240777ddc9c.png)

To get a list of your bookmarks

![image](https://user-images.githubusercontent.com/42435346/54631247-aa076900-4a8c-11e9-9111-4225e139ee45.png)

To unbookmark an article

![image](https://user-images.githubusercontent.com/42435346/54631289-c0adc000-4a8c-11e9-935d-ed0b3c1ed58d.png)

2019-03-20 10:22 UTC, wasibani-roy requested changes
Good work @Peace-Apple however in your PR you are missing a section. That section is the Description of Task to be completed section

2019-03-20 11:01 UTC, Peace-Apple commented
> Good work @Peace-Apple however in your PR you are missing a section. That section is the Description of Task to be completed section

Okay thanks Roy, let me add that

2019-03-20 11:03 UTC, CryceTruly requested changes

2019-03-20 11:03 UTC, CryceTruly commented on authors/apps/articles/models.py
> +class Bookmarks(models.Model):
Thanks for the good work @Peace-Apple, However, Django models are just Python classes, so the Python naming conventions detailed in PEP-8 apply.
The class Bookmarks should be named as Bookmark.

2019-03-20 11:14 UTC, Peace-Apple commented on authors/apps/articles/models.py
> +class Bookmarks(models.Model):
Thanks, @CryceTruly  for pointing that out, I have corrected it

2019-03-20 11:18 UTC, CryceTruly submitted a review, later dismissed

2019-03-21 09:24 UTC, wasibani-roy approved these changes

2019-03-21 09:28 UTC, CryceTruly approved these changes

2019-03-21 09:28 UTC, BagzieGracious approved these changes

2019-03-21 09:31 UTC, merged